linters:
  enable:
    - wsl
    - wrapcheck
    - errorlint
    - revive
    - noctx
    - nlreturn
    - gocritic
    - forcetypeassert
  disable:
    - gosec
    - errchkjson
  presets:
    - bugs

run:
  timeout: "30s"
