name: Go

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Build
        run: make

      - name: Test
        run: make test

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: temple
          path: ./bin/*

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: temple
          path: ./bin

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./bin/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
