name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: make

    - name: Test
      run: make test

    - name: Upload artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: temple
        path: ./bin/*
